<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>false</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PolyglotSql">
      <HintPath>..\PolyglotSql\bin\Release\netstandard2.0\PolyglotSql.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>