<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- For VS <= 2019 -->
    <TargetFrameworks Condition="'$(MSBuildVersion)' &lt; '17.0'">netstandard2.0</TargetFrameworks>
    <!-- For VS >= 2022 -->
    <TargetFrameworks Condition="'$(MSBuildVersion)' &gt;= '17.0'">netstandard2.0;net8.0</TargetFrameworks>
    <LangVersion>9.0</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <PackageId>PolyglotSql.Bundle</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>A .NET FFI wrapper for the polyglot Rust SQL transpiler. Enables high-performance parsing, formatting, AST generation, and translation between more than 30 SQL dialects.&#x0a;&#x0a;The Bundle package is intended for use out-of-the-box, it includes Polyglot binaries for win-x64, win-x86, and linux-x64 target runtimes.</Description>
	
	<!-- For .sln builds from VS, level up from $(SolutionDir) -->
	<PackageOutputPath Condition="'$(SolutionDir)' != ''">$(SolutionDir)..\LocalPackages\</PackageOutputPath>
  
	<!-- For dotnet pack of concrete csproj, 2 levels up from $(SolutionDir) -->
	<PackageOutputPath Condition="'$(SolutionDir)' == ''">$(MSBuildThisFileDirectory)..\..\LocalPackages\</PackageOutputPath>
  </PropertyGroup>

	<!-- ProjectReference for non-package build -->
	<ItemGroup Condition="'$(MSBuildPackageType)' != 'Package'">
	  <ProjectReference Include="..\PolyglotSql.Core\PolyglotSql.Core.csproj" />
	</ItemGroup>

	<!-- PackageReference for package build -->
	<ItemGroup Condition="'$(MSBuildPackageType)' == 'Package'">
	  <PackageReference Include="PolyglotSql.Core" Version="$(Version)" />
	</ItemGroup>

  <!-- for PackageReference -->
  <ItemGroup>
    <None Include="runtimes\**\*" Pack="true" PackagePath="runtimes\" />
    <None Include="PolyglotSql.Bundle.targets" Pack="true" PackagePath="build\PolyglotSql.Bundle.targets" />
    <!-- for non-direct reference -->
    <None Include="PolyglotSql.Bundle.targets" Pack="true" PackagePath="buildTransitive\PolyglotSql.Bundle.targets" />
  </ItemGroup>

  <!-- for ProjectReference -->
  <!-- Import Project="PolyglotSql.Bundle.targets" /-->

  <ItemGroup>
    <None Include="..\..\licenses\**" Pack="true" PackagePath="licenses\" />
	<None Include="..\..\THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>