<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)runtimes\win-x64\native\polyglot_sql_ffi.dll">
      <Link>runtimes\win-x64\native\polyglot_sql_ffi.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="$(MSBuildThisFileDirectory)runtimes\linux-x64\native\libpolyglot_sql_ffi.so">
      <Link>runtimes\linux-x64\native\libpolyglot_sql_ffi.so</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
