namespace PolyglotSql
{
    public enum Dialect
    {
        Generic = 0,
        PostgreSQL = 1,
        MySQL = 2,
        BigQuery = 3,
        Snowflake = 4,
        DuckDB = 5,
        SQLite = 6,
        Hive = 7,
        Spark = 8,
        Trino = 9,
        Presto = 10,
        Redshift = 11,
        TSQL = 12,
        Oracle = 13,
        ClickHouse = 14,
        Databricks = 15,
        Athena = 16,
        Teradata = 17,
        Doris = 18,
        StarRocks = 19,
        Materialize = 20,
        RisingWave = 21,
        SingleStore = 22,
        CockroachDB = 23,
        TiDB = 24,
        Druid = 25,
        Solr = 26,
        Tableau = 27,
        Dune = 28,
        Fabric = 29,
        Drill = 30,
        Dremio = 31,
        Exasol = 32,
        DataFusion = 33,
    }
}
