<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- For VS <= 2019 -->
    <TargetFrameworks Condition="'$(MSBuildVersion)' &lt; '17.0'">netstandard2.0</TargetFrameworks>
    <!-- For VS >= 2022 -->
    <TargetFrameworks Condition="'$(MSBuildVersion)' &gt;= '17.0'">netstandard2.0;net8.0</TargetFrameworks>
    <LangVersion>9.0</LangVersion>
    <RootNamespace>PolyglotSql</RootNamespace>
    <AssemblyName>PolyglotSql</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.0" />
  </ItemGroup>

</Project>
