using System;
using System.Collections.Generic;
using System.Text.Json;

namespace PolyglotSql
{
    public enum TokenType
    {
        L_PAREN = 1,
        R_PAREN = 2,
        L_BRACKET = 3,
        R_BRACKET = 4,
        L_BRACE = 5,
        R_BRACE = 6,
        COMMA = 7,
        DOT = 8,
        DASH = 9,
        PLUS = 10,
        COLON = 11,
        DOTCOLON = 12,
        DOTCARET = 13,
        DCOLON = 14,
        DCOLONDOLLAR = 15,
        DCOLONPERCENT = 16,
        DCOLONQMARK = 17,
        DQMARK = 18,
        SEMICOLON = 19,
        STAR = 20,
        BACKSLASH = 21,
        SLASH = 22,
        LT = 23,
        LTE = 24,
        GT = 25,
        GTE = 26,
        NOT = 27,
        EQ = 28,
        NEQ = 29,
        NULLSAFE_EQ = 30,
        COLON_EQ = 31,
        COLON_GT = 32,
        NCOLON_GT = 33,
        AND = 34,
        OR = 35,
        AMP = 36,
        DPIPE = 37,
        PIPE_GT = 38,
        PIPE = 39,
        PIPE_SLASH = 40,
        DPIPE_SLASH = 41,
        CARET = 42,
        CARET_AT = 43,
        TILDE = 44,
        ARROW = 45,
        DARROW = 46,
        FARROW = 47,
        HASH = 48,
        HASH_ARROW = 49,
        DHASH_ARROW = 50,
        LR_ARROW = 51,
        LLRR_ARROW = 52,
        DAT = 53,
        LT_AT = 54,
        AT_GT = 55,
        DOLLAR = 56,
        PARAMETER = 57,
        SESSION = 58,
        SESSION_PARAMETER = 59,
        SESSION_USER = 60,
        DAMP = 61,
        AMP_LT = 62,
        AMP_GT = 63,
        ADJACENT = 64,
        XOR = 65,
        DSTAR = 66,
        QMARK_AMP = 67,
        QMARK_PIPE = 68,
        HASH_DASH = 69,
        EXCLAMATION = 70,
        URI_START = 71,
        BLOCK_START = 72,
        BLOCK_END = 73,
        SPACE = 74,
        BREAK = 75,
        STRING = 76,
        NUMBER = 77,
        IDENTIFIER = 78,
        DATABASE = 79,
        COLUMN = 80,
        COLUMN_DEF = 81,
        SCHEMA = 82,
        TABLE = 83,
        WAREHOUSE = 84,
        STAGE = 85,
        STREAM = 86,
        STREAMLIT = 87,
        VAR = 88,
        BIT_STRING = 89,
        HEX_STRING = 90,
        BYTE_STRING = 91,
        NATIONAL_STRING = 92,
        RAW_STRING = 93,
        HEREDOC_STRING = 94,
        UNICODE_STRING = 95,
        BIT = 96,
        BOOLEAN = 97,
        TINYINT = 98,
        UTINYINT = 99,
        SMALLINT = 100,
        USMALLINT = 101,
        MEDIUMINT = 102,
        UMEDIUMINT = 103,
        INT = 104,
        UINT = 105,
        BIGINT = 106,
        UBIGINT = 107,
        BIGNUM = 108,
        INT128 = 109,
        UINT128 = 110,
        INT256 = 111,
        UINT256 = 112,
        FLOAT = 113,
        DOUBLE = 114,
        UDOUBLE = 115,
        DECIMAL = 116,
        DECIMAL32 = 117,
        DECIMAL64 = 118,
        DECIMAL128 = 119,
        DECIMAL256 = 120,
        DECFLOAT = 121,
        UDECIMAL = 122,
        BIGDECIMAL = 123,
        CHAR = 124,
        NCHAR = 125,
        VARCHAR = 126,
        NVARCHAR = 127,
        BPCHAR = 128,
        TEXT = 129,
        MEDIUMTEXT = 130,
        LONGTEXT = 131,
        BLOB = 132,
        MEDIUMBLOB = 133,
        LONGBLOB = 134,
        TINYBLOB = 135,
        TINYTEXT = 136,
        NAME = 137,
        BINARY = 138,
        VARBINARY = 139,
        JSON = 140,
        JSONB = 141,
        TIME = 142,
        TIMETZ = 143,
        TIME_NS = 144,
        TIMESTAMP = 145,
        TIMESTAMPTZ = 146,
        TIMESTAMPLTZ = 147,
        TIMESTAMPNTZ = 148,
        TIMESTAMP_S = 149,
        TIMESTAMP_MS = 150,
        TIMESTAMP_NS = 151,
        DATETIME = 152,
        DATETIME2 = 153,
        DATETIME64 = 154,
        SMALLDATETIME = 155,
        DATE = 156,
        DATE32 = 157,
        INT4RANGE = 158,
        INT4MULTIRANGE = 159,
        INT8RANGE = 160,
        INT8MULTIRANGE = 161,
        NUMRANGE = 162,
        NUMMULTIRANGE = 163,
        TSRANGE = 164,
        TSMULTIRANGE = 165,
        TSTZRANGE = 166,
        TSTZMULTIRANGE = 167,
        DATERANGE = 168,
        DATEMULTIRANGE = 169,
        UUID = 170,
        GEOGRAPHY = 171,
        GEOGRAPHYPOINT = 172,
        NULLABLE = 173,
        GEOMETRY = 174,
        POINT = 175,
        RING = 176,
        LINESTRING = 177,
        LOCALTIME = 178,
        LOCALTIMESTAMP = 179,
        SYSTIMESTAMP = 180,
        MULTILINESTRING = 181,
        POLYGON = 182,
        MULTIPOLYGON = 183,
        HLLSKETCH = 184,
        HSTORE = 185,
        SUPER = 186,
        SERIAL = 187,
        SMALLSERIAL = 188,
        BIGSERIAL = 189,
        XML = 190,
        YEAR = 191,
        USERDEFINED = 192,
        MONEY = 193,
        SMALLMONEY = 194,
        ROWVERSION = 195,
        IMAGE = 196,
        VARIANT = 197,
        OBJECT = 198,
        INET = 199,
        IPADDRESS = 200,
        IPPREFIX = 201,
        IPV4 = 202,
        IPV6 = 203,
        ENUM = 204,
        ENUM8 = 205,
        ENUM16 = 206,
        FIXEDSTRING = 207,
        LOWCARDINALITY = 208,
        NESTED = 209,
        AGGREGATEFUNCTION = 210,
        SIMPLEAGGREGATEFUNCTION = 211,
        TDIGEST = 212,
        UNKNOWN = 213,
        VECTOR = 214,
        DYNAMIC = 215,
        VOID = 216,
        ALIAS = 217,
        ALTER = 218,
        ALL = 219,
        ANTI = 220,
        ANY = 221,
        APPLY = 222,
        ARRAY = 223,
        ASC = 224,
        ASOF = 225,
        ATTACH = 226,
        AUTO_INCREMENT = 227,
        BEGIN = 228,
        BETWEEN = 229,
        BULK_COLLECT_INTO = 230,
        CACHE = 231,
        CASE = 232,
        CHARACTER_SET = 233,
        CLUSTER_BY = 234,
        COLLATE = 235,
        COMMAND = 236,
        COMMENT = 237,
        COMMIT = 238,
        CONNECT_BY = 239,
        CONSTRAINT = 240,
        COPY = 241,
        CREATE = 242,
        CROSS = 243,
        CUBE = 244,
        CURRENT_DATE = 245,
        CURRENT_DATETIME = 246,
        CURRENT_SCHEMA = 247,
        CURRENT_TIME = 248,
        CURRENT_TIMESTAMP = 249,
        CURRENT_USER = 250,
        CURRENT_USER_ID = 251,
        CURRENT_ROLE = 252,
        CURRENT_CATALOG = 253,
        DECLARE = 254,
        DEFAULT = 255,
        DELETE = 256,
        DESC = 257,
        DESCRIBE = 258,
        DETACH = 259,
        DICTIONARY = 260,
        DISTINCT = 261,
        DISTRIBUTE_BY = 262,
        DIV = 263,
        DROP = 264,
        ELSE = 265,
        END = 266,
        ESCAPE = 267,
        EXCEPT = 268,
        EXECUTE = 269,
        EXISTS = 270,
        FALSE = 271,
        FETCH = 272,
        FILE = 273,
        FILE_FORMAT = 274,
        FILTER = 275,
        FINAL = 276,
        FIRST = 277,
        FOR = 278,
        FORCE = 279,
        FOREIGN_KEY = 280,
        FORMAT = 281,
        FROM = 282,
        FULL = 283,
        FUNCTION = 284,
        GET = 285,
        GLOB = 286,
        GLOBAL = 287,
        GRANT = 288,
        GROUP_BY = 289,
        GROUPING_SETS = 290,
        HAVING = 291,
        HINT = 292,
        IGNORE = 293,
        ILIKE = 294,
        IN = 295,
        INDEX = 296,
        INDEXED_BY = 297,
        INNER = 298,
        INSERT = 299,
        INSTALL = 300,
        INTEGRATION = 301,
        INTERSECT = 302,
        INTERVAL = 303,
        INTO = 304,
        INTRODUCER = 305,
        IRLIKE = 306,
        IS = 307,
        ISNULL = 308,
        JOIN = 309,
        JOIN_MARKER = 310,
        KEEP = 311,
        KEY = 312,
        KILL = 313,
        LANGUAGE = 314,
        LATERAL = 315,
        LEFT = 316,
        LIKE = 317,
        LIMIT = 318,
        LIST = 319,
        LOAD = 320,
        LOCK = 321,
        MAP = 322,
        MATCH = 323,
        MATCH_CONDITION = 324,
        MATCH_RECOGNIZE = 325,
        MEMBER_OF = 326,
        MERGE = 327,
        MOD = 328,
        MODEL = 329,
        NATURAL = 330,
        NEXT = 331,
        NOTHING = 332,
        NOTNULL = 333,
        NULL = 334,
        OBJECT_IDENTIFIER = 335,
        OFFSET = 336,
        ON = 337,
        ONLY = 338,
        OPERATOR = 339,
        ORDER_BY = 340,
        ORDER_SIBLINGS_BY = 341,
        ORDERED = 342,
        ORDINALITY = 343,
        OUT = 344,
        INOUT = 345,
        OUTER = 346,
        OVER = 347,
        OVERLAPS = 348,
        OVERWRITE = 349,
        PACKAGE = 350,
        PARTITION = 351,
        PARTITION_BY = 352,
        PERCENT = 353,
        PIVOT = 354,
        PLACEHOLDER = 355,
        POLICY = 356,
        POOL = 357,
        POSITIONAL = 358,
        PRAGMA = 359,
        PREWHERE = 360,
        PRIMARY_KEY = 361,
        PROCEDURE = 362,
        PROPERTIES = 363,
        PSEUDO_TYPE = 364,
        PUT = 365,
        QUALIFY = 366,
        QUOTE = 367,
        QDCOLON = 368,
        RANGE = 369,
        RECURSIVE = 370,
        REFRESH = 371,
        RENAME = 372,
        REPLACE = 373,
        RETURNING = 374,
        REVOKE = 375,
        REFERENCES = 376,
        RIGHT = 377,
        RLIKE = 378,
        ROLE = 379,
        ROLLBACK = 380,
        ROLLUP = 381,
        ROW = 382,
        ROWS = 383,
        RULE = 384,
        SELECT = 385,
        SEMI = 386,
        SEPARATOR = 387,
        SEQUENCE = 388,
        SERDE_PROPERTIES = 389,
        SET = 390,
        SETTINGS = 391,
        SHOW = 392,
        SIMILAR_TO = 393,
        SOME = 394,
        SORT_BY = 395,
        SOUNDS_LIKE = 396,
        SQL_SECURITY = 397,
        START_WITH = 398,
        STORAGE_INTEGRATION = 399,
        STRAIGHT_JOIN = 400,
        STRUCT = 401,
        SUMMARIZE = 402,
        TABLE_SAMPLE = 403,
        TAG = 404,
        TEMPORARY = 405,
        TOP = 406,
        THEN = 407,
        TRUE = 408,
        TRUNCATE = 409,
        TRIGGER = 410,
        TYPE = 411,
        UNCACHE = 412,
        UNION = 413,
        UNNEST = 414,
        UNPIVOT = 415,
        UPDATE = 416,
        USE = 417,
        USING = 418,
        VALUES = 419,
        VARIADIC = 420,
        VIEW = 421,
        SEMANTIC_VIEW = 422,
        VOLATILE = 423,
        VOLUME = 424,
        WHEN = 425,
        WHERE = 426,
        WINDOW = 427,
        WITH = 428,
        UNIQUE = 429,
        UTC_DATE = 430,
        UTC_TIME = 431,
        UTC_TIMESTAMP = 432,
        VERSION_SNAPSHOT = 433,
        TIMESTAMP_SNAPSHOT = 434,
        OPTION = 435,
        SINK = 436,
        SOURCE = 437,
        ANALYZE = 438,
        NAMESPACE = 439,
        EXPORT = 440,
        HIVE_TOKEN_STREAM = 441,
        SENTINEL = 442,
    }

    public class Token
    {
        public TokenType TokenType { get; set; }
        public string Text { get; set; } = "";
        public int Line { get; set; }
        public int Col { get; set; }
        public int Start { get; set; }
        public int End { get; set; }
        public List<string>? Comments { get; set; }
    }

    public class Tokenizer
    {
        public List<Token> Tokenize(string sql, Dialect dialect = Dialect.Generic)
        {
            string json = Polyglot.Tokenize(sql, dialect);
            return ParseTokens(json);
        }

    private List<Token> ParseTokens(string json)
    {
        var tokens = new List<Token>();
        using var doc = JsonDocument.Parse(json);
        foreach (var element in doc.RootElement.EnumerateArray())
        {
            var token = new Token
            {
                TokenType = ParseTokenType(element.GetProperty("token_type")),
                Text = element.GetProperty("text").GetString() ?? "",
            };

            if (element.TryGetProperty("span", out var span))
            {
                token.Line = ParseJsonInt(span.GetProperty("line")) - 1;
                token.Col = ParseJsonInt(span.GetProperty("column")) - 1;
                token.Start = ParseJsonInt(span.GetProperty("start"));
                token.End = ParseJsonInt(span.GetProperty("end")) - 1;
            }

            if (element.TryGetProperty("comments", out var comments) && comments.ValueKind == JsonValueKind.Array)
            {
                token.Comments = new List<string>();
                foreach (var comment in comments.EnumerateArray())
                {
                    token.Comments.Add(comment.GetString() ?? "");
                }
            }

            tokens.Add(token);
        }
        return tokens;
    }

    private TokenType ParseTokenType(JsonElement element)
    {
        if (element.ValueKind == JsonValueKind.Number)
            return (TokenType)element.GetInt32();
        if (element.ValueKind == JsonValueKind.String && Enum.TryParse<TokenType>(element.GetString(), out var result))
            return result;
        return TokenType.UNKNOWN;
    }

    private int ParseJsonInt(JsonElement element)
    {
        if (element.ValueKind == JsonValueKind.Number)
            return element.GetInt32();
        if (element.ValueKind == JsonValueKind.String && int.TryParse(element.GetString(), out var result))
            return result;
        return 0;
    }
    }
}
