<Project>
	<PropertyGroup>
		<Version>0.3.0</Version>
		<Authors>Konstantin Semenenkov</Authors>
		<Company>KS DB Merge Tools</Company>
		<Copyright>Copyright © Konstantin Semenenkov (KS DB Merge Tools) 2026</Copyright> 
		<PackageTags>sql;ast;transpiler;parser;polyglot;sqlglot</PackageTags>
		<RepositoryUrl>https://github.com/KS-DB-Merge-Tools/polyglot-sql-net</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://ksdbmerge.tools</PackageProjectUrl> 
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>
</Project>
